# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: My Envio Indexer
description: My Envio Indexer
field_selection:
  transaction_fields:
    - "hash"
    - "transactionIndex"
    - "gasUsed"
  block_fields:
    - "parentHash"
networks:
  - id: 10
    # op: 10, arbitrum: 42161, scroll: 534352, sepolia: 11155111, zksync-era: 324, base: 8453
    start_block: 115319405 # optimism
    # start_block: 2817659 # scroll
    # start_block: 174675651 # arbitrum-one
    # start_block: 5154924 # sepolia
    # start_block: 28355028 # zksync-era
    # start_block: 23993821 # base
    contracts:
      - name: HappyRedPacket
        address: 0x62E8cf62Dc0B7d7afF9A1A58CeA14976fDB16a85 # optimism
        # address: 0xC90D844679C0eFEB37522c43711D4856d192BD62 # scroll
        # address: 0x075FE5D2CD5D22D744Da94d81658143abf49D589 # arbitrum
        # address: 0x7aee9933802d9E150e8FdEDc5a022a6d386BB44d # sepolia
        # address: 0x0Aa38Cffc6A72e6349c8bfF22497AeC4A02fc75c # zksync-era
        # address: 0xeDF822CC298241A65326AaF314697a25B4B7CDE5 # base
        handler: src/EventHandlers.ts
        events:
          - event: ClaimSuccess(bytes32 id, address claimer, uint256 claimed_value, address token_address, bytes32 lock)
          - event: CreationSuccess(uint256 total, bytes32 id, string name, string message, address creator, uint256 creation_time, address token_address, uint256 number, bool ifrandom, uint256 duration, bytes32 lock)
          - event: RefundSuccess(bytes32 id, address token_address, uint256 remaining_balance, bytes32 lock)
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
